trigger: none

pool:
  # AzureStaticWebApp@0 requires Docker to be installed
  vmImage: ubuntu-20.04

stages:

- stage: prod
  dependsOn: [] 
  variables:
  - group: Docs-prod
  jobs:
    - job:
      displayName: deploy
      steps:
        - task: AzureStaticWebApp@0
          inputs:
            app_location: '/'
            api_location: ''
            output_location: 'build'
            azure_static_web_apps_api_token: $(AzureStaticWebAppDeploymentToken)
