trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: 'run build'

- task: WhiteSource@21
  displayName: 'WhiteSource Scan'
  inputs:
    projectName: 'tapio.Docs'
